<a href="https://colab.research.google.com/github/srikanth1998/DAV-5400/blob/master/DAV_500_M3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DAV 5400 Module 2 Assignment**

**Srikanth Burra**

**1. Your task is to replace each odd number with a value of -10 using only a single line of Python code.**

In [15]:
#NumPy is a library for the Python programming language, adding support for large high-level mathematical functions to operate on these arrays. 
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#if the functionality in the  sqare brakets get true then '-10' will be assigned to particular index
arr[arr % 2  == 1] = -10

#printing an array
arr


array([  0, -10,   2, -10,   4, -10,   6, -10,   8, -10])

**2. Your task is to convert that 1-dimensional array to a 2-dimensional array containing 2 rows using only a single line of Python code.**

In [18]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

#resape is an inbuilt function, whic takes two parameters n1 and n2 , which converts aray into , n1 rows and n2 columns
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**3. Your task is to extract all items from that array that fall between 5 and 12 (inclusive) using only a single line of Python code**

In [22]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

#traversing through the array and checking the conditions and storing in te array
arr[(arr >= 5) & (arr <= 12)] 


array([5, 6, 7, 8, 9])

**4. Your task is to swap the first and second rows of that array using only a single line of Python code.**

In [24]:
#arranging the 10 elements in 3x3 matrix
arr = np.arange(9).reshape(3,3)

#swaping matrix by row index, as 1->0 and 0->1
arr[[1,0,2], :] 


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])